# Generated by Django 2.0.13 on 2020-11-04 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actel',
            fields=[
                ('aid', models.AutoField(primary_key=True, serialize=False)),
                ('agenceid', models.CharField(max_length=50)),
                ('nom', models.CharField(max_length=50)),
                ('adress', models.CharField(max_length=200)),
                ('nbragent', models.IntegerField()),
                ('isactive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('clientid', models.CharField(max_length=50)),
                ('jour', models.DateField(blank=True, null=True)),
                ('timee', models.DateTimeField()),
                ('timel', models.DateTimeField()),
                ('times', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Contain',
            fields=[
                ('containid', models.AutoField(primary_key=True, serialize=False)),
                ('aid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Actel')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('did', models.AutoField(primary_key=True, serialize=False)),
                ('jour', models.DateField(blank=True, null=True)),
                ('nbragent', models.IntegerField()),
                ('nbrclient', models.IntegerField()),
                ('attmoy', models.IntegerField()),
                ('maxt', models.IntegerField()),
                ('mint', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fontionnalite',
            fields=[
                ('fid', models.AutoField(primary_key=True, serialize=False)),
                ('gerercompte', models.BooleanField(default=False)),
                ('gereragence', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gerer',
            fields=[
                ('gererid', models.AutoField(primary_key=True, serialize=False)),
                ('aid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Actel')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Peut',
            fields=[
                ('peutid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Possed',
            fields=[
                ('possedid', models.AutoField(primary_key=True, serialize=False)),
                ('fid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Fontionnalite')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profileid', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('compteid', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('nom', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('agence', models.CharField(max_length=100)),
                ('apassword', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('simpleuser', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('superadmin', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('visitid', models.AutoField(primary_key=True, serialize=False)),
                ('aid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Actel')),
                ('cid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Client')),
            ],
        ),
        migrations.AddField(
            model_name='possed',
            name='rid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Role'),
        ),
        migrations.AddField(
            model_name='peut',
            name='rid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Role'),
        ),
        migrations.AddField(
            model_name='peut',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contain',
            name='did',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Data'),
        ),
    ]
