# Generated by Django 2.0.13 on 2020-11-04 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
