# Generated by Django 2.0.13 on 2020-11-13 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201104_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contain',
            name='aid',
        ),
        migrations.RemoveField(
            model_name='contain',
            name='did',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='aid',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='cid',
        ),
        migrations.AddField(
            model_name='client',
            name='aid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Actel'),
        ),
        migrations.AddField(
            model_name='data',
            name='aid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Actel'),
        ),
        migrations.AddField(
            model_name='profile',
            name='aid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Actel'),
        ),
        migrations.AlterField(
            model_name='gerer',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Profile'),
        ),
        migrations.AlterField(
            model_name='peut',
            name='userid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Profile'),
        ),
        migrations.DeleteModel(
            name='Contain',
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
